version: '3.8'



services:

  postgres-container:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8086:8085"
    depends_on:
      - postgres-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always

volumes:
    posgres_data:
