name: Java Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Find pom.xml
      id: find-pom
      run: |
        FILE=$(find . -name "pom.xml" | head -n 1)
        if [ -z "$FILE" ]; then
          echo "No pom.xml file found in the repository."
          exit 1
        fi
        echo "POM file found: $FILE"
        echo "pom-path=$FILE" >> $GITHUB_ENV
    
    - name: Build project
      run: mvn clean package -f ${{ env.pom-path }} -DskipTests
    
    - name: Run tests (if any)
      continue-on-error: true
      run: |
        if [ -d "src/test" ]; then
          mvn test -f ${{ env.pom-path }}
        else
          echo "No test directory found, skipping tests"
        fi
